from setuptools import setup

setup(name='pytest-mozversion',
      use_scm_version=True,
      description='pytest plugin for extracting Mozilla version metadata',
      long_description=open('README.rst').read(),
      author='Dave Hunt',
      author_email='dhunt@mozilla.com',
      url='https://github.com/davehunt/pytest-mozversion',
      packages=['pytest_mozversion'],
      entry_points={'pytest11': ['mozversion = pytest_mozversion.plugin']},
      setup_requires=['setuptools_scm'],
      install_requires=[
        'pytest>=2.9.0',
        'pytest-base-url',
        'pytest-metadata',
        'requests'],
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='py.test pytest mozilla version mozversion',
      classifiers=[
          'Development Status :: 5 - Production/Stable',
          'Framework :: Pytest',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
          'Operating System :: POSIX',
          'Operating System :: Microsoft :: Windows',
          'Operating System :: MacOS :: MacOS X',
          'Topic :: Software Development :: Quality Assurance',
          'Topic :: Software Development :: Testing',
          'Topic :: Utilities',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3.6'])
